sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tFRBHsh8XavG3UKY7oc
    access-key-secret: 03sxV544qyo8efoyu20nugeuuJjp1q
    bucket-name: take-away-sierra
